on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [opened, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21"]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.21.0
          aqua_opts: "-l"
      - run: make build
